name: 'Trigger a Pipedream workflow'
author: 'Douglas Harcourt Parsons'
description: 'Triggers a series of deployments'
inputs:
  secret:
    description: 'Pipedream secret'
    required: true
  github-token:
    description: 'Github Token to use for triggering workflows'
    required: true
  workflow:
    description: 'Workflow file to trigger'
    required: true
  stabilityPeriodMinutes:
    description: 'Amount of time to leave in between deployments, in minutes'
    required: true
  environments:
    description: 'Comma separated, ordered list of environment identifiers to be deployed'
    required: true
outputs:
  url:
    description: 'URL to visit the workflow progress in Pipedream'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'triangle'
  color: 'white'
